### PR TITLE
Fix calculation of events repeating every X weeks

### LINKED ISSUE #408: "Repeat every X weeks" is broken in certain time zones
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.0

### Affected Android/Custom ROM version

Android 14

### Affected device model

Emulator

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

1. Set the time zone to Antarctica/McMurdo
2. Create an event on Monday 11 March 2024 at 9am with custom repetition every 3 weeks
3. View the occurrences of the event

### Expected behavior

The occurrences should be:
Mon 11 Mar 2024
Mon 01 Apr 2024
Mon 22 Apr 2024
Mon 13 May 2024

### Actual behavior

The occurrences are:
Mon 11 Mar 2024
Mon 01 Apr 2024
**Mon 15 Apr 2024** (**incorrect** -- gap is 2 weeks instead of 3)
**Mon 06 May 2024**

### Screenshots/Screen recordings

1-set-time-zone 2-event-details 3-occurrences-march 4-occurrences-april

Observe how in the final screenshot (April) the occurrences are incorrect.

### Analysis

The bug is in the method isOnProperWeek in [models/Event.k](https://github.com/FossifyOrg/Calendar/blob/1.1.0/app/src/main/kotlin/org/fossify/calendar/models/Event.kt#L178-L184).

It calculates the week number of a timestamp by taking the start-of-day (in the default time zone) as a Unix timestamp then dividing by 7 weeks and rounding to the nearest integer. This works in most cases, but is actually wrong. It mostly works because:
- The Unix epoch is Thursday 00:00 UTC.
- So timestamps within 3.5 days of Thu 00:00 UTC are rounded to the same week number.
- So the threshold is Sunday 12:00 UTC.
- In most time zones, the start-of-day of Sunday is before Sunday 12:00 UTC, and the start-of-day of Monday is after Sunday 12:00 UTC. So in most time zones the calculation assigns the same week number to Mon-Sun.

However, this breaks in time zones such as Antarctica/McMurdo, because in that time zone the start-of-day of Monday is very close to Sunday 12:00 UTC, so the rounding is unstable, and daylight saving causes the calculation to produce an incorrect week number.

### PR DESCRIPTION
**Pull request by tom93**
#### What is it?
- [x] Bugfix
- [ ] Feature
- [ ] Codebase improvement

#### Description of the changes in your PR
- Fix calculation of events repeating every X weeks. The previous implementation was broken in some time zones (see [#408](https://github.com/FossifyOrg/Calendar/issues/408) for details).

#### Fixes the following issue(s)
- Fixes #408

#### Comments

This PR hard-codes the start of the week to be Monday, to match the previous behaviour. Ideally this should be configurable (I added a TODO comment with notes).

Like the previous implementation, the new code uses the default time zone, ignoring the event's time zone. This is a bug and should be fixed, but will probably require significant changes so I did not attempt to do it. I suspect that's the root cause of #165.

Code review comment for existing code: The method takes a parameter `startTimes: LongSparseArray<Long>` in which it does a lookup by the event ID. I don't see any reason to pass an array with all the event start times. I might create a PR to only pass the start time of the event currently being considered.

#### Acknowledgement
- [x] I read the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### CODE REVIEW

File: app/src/main/kotlin/org/fossify/calendar/models/Event.kt [hunk 1]
```diff
@@ -176,11 +178,18 @@ data class Event(
...
 
     // check if it's the proper week, for events repeating every x weeks
-    // get the week number since 1970, not just in the current year
     fun isOnProperWeek(startTimes: LongSparseArray<Long>): Boolean {
-        val initialWeekNumber = Formatter.getDateTimeFromTS(startTimes[id!!]!!).withTimeAtStartOfDay().millis / (7 * 24 * 60 * 60 * 1000f)
-        val currentWeekNumber = Formatter.getDateTimeFromTS(startTS).withTimeAtStartOfDay().millis / (7 * 24 * 60 * 60 * 1000f)
-        return (Math.round(initialWeekNumber) - Math.round(currentWeekNumber)) % (repeatInterval / WEEK) == 0
+        // TODO: The start of the week is currently hard-coded to be Monday. It should be configurable.
+        // For reference, Google Calendar uses the value of the "Start of the week" setting at the time the event is created/edited.
+        // (The start of the week is significant for events that repeat on multiple days of the week.)
```
Comment (naveensingh) [inline app/src/main/kotlin/org/fossify/calendar/models/Event.kt:184]: @tom93 

Please ignore if this comment is a result of my swift analysis but don't we already have a "Start week on" option?

Comment (tom93) [reply app/src/main/kotlin/org/fossify/calendar/models/Event.kt:184]: Yes, I meant that in future this code should be updated to respect that existing option.

(To be clear, this is about what happens when you create an event that repeats every X weeks with some X > 1 and you also set it to repeat on multiple days of the week.)

I didn't attempt to make it configurable because it's non-trivial. The simplest approach (which I think is wrong) would be to use the current value of the option. But that means that when the user changes the option, it will affect the occurrences of existing events (which I find unacceptable).

Instead, I think we should match Google Calendar's behaviour: add a hidden property to each event recording its start-of-week, and when an event is created (or when its repeat rule is edited) set the event's start-of-week to the current value of the global option. The iCal format supports per-event start-of-week.

**Comment by tom93** [comment]
Oops, I had a bug (detekt correctly pointed out that the variable initialWeekStart was unused). I force-pushed a fix, testing it now.
I also tried to fix the other detekt style warnings. I removed the word "TODO" because Detekt's default rules forbid it, but I strongly disagree with that rule.

**Comment by tom93** [comment]
I finished testing and I'm happy with it. (The last force-push was just to bring it up to date with master.)

**Comment by naveensingh** [comment]
Tested this in some time-zones and it works fine. The updated logic looks correct as well, thanks!

> The method takes a parameter startTimes: LongSparseArray<Long> in which it does a lookup by the event ID. I don't see any reason to pass an array with all the event start times. I might create a PR to only pass the start time of the event currently being considered.

Probably a result a confusion due to the fact that `event.startTS` is updated by the `while` loop. Directly passing `original.startTS` shouldn't cause any issues.
